@url = http://localhost:3000/api


GET {{url}}/health-check

###
GET {{url}}/products/63dcb321448df0d273100a40

###
POST {{url}}/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2RkMjlhZjhlZWM3NWFkMDU2ZjllMDEiLCJpYXQiOjE2NzU0Mzg1MjksImV4cCI6MTY3NTQzOTQyOX0.G_tX45bnQ0XRHw0MOAW82cBsseVXhN4B2wN9L8btLDU

{
   "title": "Code dao ky su",
   "description": "A like-new experience. Backed by a one-year satisfaction guarantee. This Renewed Premium product is shipped and sold by Amazon and has been certified by Amazon to work and look like new. With at least 90% battery life, it comes in deluxe, Amazon-branded packaging and is backed by a one-year warranty and technical support.",
   "price": 129000,
   "image": "https://cdn2.cellphones.com.vn/358x358,webp,q100/media/catalog/product/t/_/t_m_12.png"
}

###
PUT {{url}}/products/63dcb2ea448df0d273100a34
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2Q0Y2Q4ZGY4MjgyZjBmNjg3ZjgzYTAiLCJpYXQiOjE2NzU0MDgwODEsImV4cCI6MTY3NTQwODk4MX0.qS-1_rkqeWgOVck7ARM305TNn9gmrFn5RXd61eDNZAY

{
   "title": "Clean code",
   "description": "A like-new experience. Backed by a one-year satisfaction guarantee. This Renewed Premium product is shipped and sold by Amazon and has been certified by Amazon to work and look like new. With at least 90% battery life, it comes in deluxe, Amazon-branded packaging and is backed by a one-year warranty and technical support.",
   "price": 1640000,
   "image": "https://cdn2.cellphones.com.vn/358x358,webp,q100/media/catalog/product/t/_/t_m_12.png"
}

###
DELETE  {{url}}/products/63dcb321448df0d273100a40
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2Q0Y2Q4ZGY4MjgyZjBmNjg3ZjgzYTAiLCJpYXQiOjE2NzU0MDgwODEsImV4cCI6MTY3NTQwODk4MX0.qS-1_rkqeWgOVck7ARM305TNn9gmrFn5RXd61eDNZAY
