@url = http://localhost:3000/api


GET {{url}}/health-check

###
POST {{url}}/users/signup
content-type: application/json

{
   "email": "travis@gmail.com",
   "name": "travis",
   "password": "123456",
   "passwordConfirmation": "123456"
}

###
POST {{url}}/users/signin
content-type: application/json

{
   "email": "tranl@gmail.com",
   "password": "123456"
}

###
DELETE  {{url}}/users/logout
content-type: application/json

{
   "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2Q0Y2Q4ZGY4MjgyZjBmNjg3ZjgzYTAiLCJpYXQiOjE2NzUwNjIyMTcsImV4cCI6MTcwNjU5ODIxN30.jp8g6LCvmNcbnaF2xOszNSpGN6vT_07--EnPH2JXUsI"
}

###
POST {{url}}/users/reissue-token
content-type: application/json

{
   "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2Q0Y2Q4ZGY4MjgyZjBmNjg3ZjgzYTAiLCJpYXQiOjE2NzQ5ODk4NzksImV4cCI6MTcwNjUyNTg3OX0.DPeQZ19SYgwcOvmRHoLmAjuwt1ezcodZZS8D1CfiPPo"
}

###
GET {{url}}/products/63d645fa95d7c852b8be9d55

###
POST {{url}}/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2Q0Y2Q4ZGY4MjgyZjBmNjg3ZjgzYTAiLCJpYXQiOjE2NzQ5ODY0MjIsImV4cCI6MTY3NTA3MjgyMn0.kgbH4h1qiPisZ5vPRDZ_IBTb6S1RDKMyHCLznUtRAAY

{
   "title": "Code dao ky su",
   "description": "A like-new experience. Backed by a one-year satisfaction guarantee. This Renewed Premium product is shipped and sold by Amazon and has been certified by Amazon to work and look like new. With at least 90% battery life, it comes in deluxe, Amazon-branded packaging and is backed by a one-year warranty and technical support.",
   "price": 129000,
   "image": "https://cdn2.cellphones.com.vn/358x358,webp,q100/media/catalog/product/t/_/t_m_12.png"
}

###
PUT {{url}}/products/63d6460a95d7c852b8be9d58
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2Q0Y2Q4ZGY4MjgyZjBmNjg3ZjgzYTAiLCJpYXQiOjE2NzQ5ODY0MjIsImV4cCI6MTY3NTA3MjgyMn0.kgbH4h1qiPisZ5vPRDZ_IBTb6S1RDKMyHCLznUtRAAY

{
   "title": "Clean code",
   "description": "A like-new experience. Backed by a one-year satisfaction guarantee. This Renewed Premium product is shipped and sold by Amazon and has been certified by Amazon to work and look like new. With at least 90% battery life, it comes in deluxe, Amazon-branded packaging and is backed by a one-year warranty and technical support.",
   "price": 1640000,
   "image": "https://cdn2.cellphones.com.vn/358x358,webp,q100/media/catalog/product/t/_/t_m_12.png"
}

###
DELETE  {{url}}/products/63d6460a95d7c852b8be9d58
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2Q0Y2Q4ZGY4MjgyZjBmNjg3ZjgzYTAiLCJpYXQiOjE2NzQ5ODY0MjIsImV4cCI6MTY3NTA3MjgyMn0.kgbH4h1qiPisZ5vPRDZ_IBTb6S1RDKMyHCLznUtRAAY
